services:
  web:
    build:
      context: ./website/
      target: dev
    ports:
      - "5000:5000"
    depends_on:
      - server
    volumes:
      - ./website/app:/app/app
      - ./website/components:/app/components
      - ./website/utils:/app/utils

  server:
    build: 
      context: .
      target: dev
    ports:
      - "5001:5001"
    volumes:
      - ./db:/code/db
      - ./internal:/code/internal
      - ./engine:/code/engine/
      - ./assets/thumbnails:/code/assets/thumbnails/
