services:
  web:
    build: ./client/
    ports:
      - "5000:5000"
    depends_on:
      - server

  server:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./db/data.db:/code/db/data.db:rw
      - ./assets/thumbnails:/code/assets/thumbnails/