services:
  web:
    build: 
      context: ./website
      target: prod
    ports:
      - "5000:5000"
    depends_on:
      - server

  server:
    build: 
      context: .
      target: prod
    ports:
      - "5001:5001"
    volumes:
      - ./db:/code/db
      - ./engine:/code/engine/
      - ./internal:/code/internal
      - ./assets/thumbnails:/code/assets/thumbnails/